name: SprucyInc
favicon: null
layout_spectrum: 0.5923278036061674
typography_spectrum: 0.5822630973998457
title: Sprucy Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#34495e'
    - '#3dc676'
    - '#a6afb8'
    - '#ff8a16'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
